name: CustomWarps
version: '${project.version}'
main: top.ilhyc.customwarps.customwarps
description: just the customwarps
softdepend: [Multiverse-Core,Vault]
commands:
  customwarps:
    aliases: cw
  cset:
  climit:
    aliases: clt
